### ISSUE TITLE
Suggestion: Fluids

### ISSUE THREAD

**Issue by pyure** [V0idWa1k3r/Factory0-Resources#1]
V0idWa1k3r, this looks fantastic.  

Would your mechanisms be reasonably adaptable to fluid extraction? 

If so, I'd like to suggest "fluids are resources too", and allow extraction of fluids (oils, gases, etc).

**Comment by V0idWa1k3r** [comment]
Sure, seems reasonable. With a mechanical/burner pumps able to extract fluids.
What item would you use to prospect for fluids though? A prospector's tool doesn't cut it here.

**Comment by TedKnudsen** [comment]
Thanks for considering it.  

My first amusing thought is a dowsing stick, of divination lore.
https://en.wikipedia.org/wiki/Dowsing

Probably not appropriate for your theme however :)

In actuality, I'm not certain which tools would cover the most use-cases in a reasonably logical and universal fashion.  Exploration for fluids and gases varies massively in methodology depending on the type of fluid/gas being sought.

To be honest I would have accepted the prospector's tool just fine as an abstract "tool that separates samples in soil for general analysis".   It keeps things simple and streamlined on your side, and removes the need for players to carry an extra item around on our side.

**Comment by pyure** [comment]
Thanks for considering it.

My first amusing thought is a dowsing stick, of divination lore.
https://en.wikipedia.org/wiki/Dowsing

Probably not appropriate for your theme however :)

In actuality, I'm not certain which tools would cover the most use-cases in a reasonably logical and universal fashion. Exploration for fluids and gases varies massively in methodology depending on the type of fluid/gas being sought.

To be honest I would have accepted the prospector's tool just fine as an abstract "tool that separates samples in soil for general analysis". It keeps things simple and streamlined on your side, and removes the need for players to carry an extra item around on our side.

**Comment by TedKnudsen** [comment]
Wow that was quick!

**Comment by pyure** [comment]
Wow that was quick! :)
