### ISSUE TITLE
[Bug] Drills consume power, but doesn't generate ores

### ISSUE THREAD

**Issue by Desempregago** [V0idWa1k3r/Factory0-Resources#13]
The title explains itself.

Both Burner and Powered Drills doesn't generate power, but keep consuming power

Mod version: 1.0.3.1
Latest Forge (2838)

**Comment by Desempregago** [comment]
Also, the drill head doesn't even spin

**Comment by Golrith** [comment]
Have you remembered to shift-rightclick a side to set the output face?

Drills will also consume power/fuel if there is nothing in the chunk to mine.

**Comment by Desempregago** [comment]
Wait, was this a requirement? I didn't see this in the drill setup instructions

**Comment by AbieTheFishman** [comment]
Thanks, I missed this also
