### ISSUE TITLE
Extracts ore in a super flat world

### ISSUE THREAD

**Issue by Lukmores** [V0idWa1k3r/Factory0-Resources#3]
Wat!?)
![image](https://user-images.githubusercontent.com/12397855/44306249-22e1fd80-a3a4-11e8-89a8-1fe8cb6d955c.png)
![image](https://user-images.githubusercontent.com/12397855/44306267-6ccae380-a3a4-11e8-80a9-efb500086450.png)

normal world, he will also spawn ore.

**Comment by V0idWa1k3r** [comment]
This is an intended behaviour. The ores are not physically spawned/mined from the world. Instead they exist as an "abstract number" stored to a chunk. The drills don't physically mine ores, they "create them out of thin air" while decrementing that "abstract number".
