### ISSUE TITLE
Placeable ore veins

### ISSUE THREAD

**Issue by Smolk14** [V0idWa1k3r/Factory0-Resources#5]
I would like to request a feature: A toggle in the config to disable the algorithmic ore vein generation and a tool (or command) to place a vein of a specified ore and size in a given chunk.
The reason i would like this feature is for a server i am planing (would like to have specific spots for each ore guarded by monsters)
I would be realy gratefull if you implemented this feature

**Comment by V0idWa1k3r** [comment]
How would you place an ore vein of a size 20000 for example? That's a lot of blocks(1/3 of a chunk). Will that just replace everything up to ground level with ore?

**Comment by Smolk14** [comment]
By "ore vein" i ment the virtual one that is accesed by the drill  (not actual  blocks)

**Comment by V0idWa1k3r** [comment]
Ah I see, you don't actually want to generate the vein physically. 
There is currently a /f0r command that allows you to manually place/remove/edit ore veins. Use /for help to get the syntax for it. You can disable the ore generation by either removing all entries from the ores.json or by editing them in such a way that the oreMinimum is greater or equal to 1.

**Comment by Smolk14** [comment]
Oh i was not aware of that command, Thanks for your help
