### ISSUE TITLE
seismic Reader (missing recipe)(others)

### ISSUE THREAD

**Issue by Lightone** [V0idWa1k3r/Factory0-Resources#6]
no energy usage and missing recipe (creative only ? )
Mod version  Factory0-Resources-1.12.2-1.0.3.1

suggestion:Not only (you are here) but more details, add the color the chunck where are you located (blue o red )

**Comment by V0idWa1k3r** [comment]
Seismic reader is a creative-only item designed to help map makers visualize the ore gen with the parameters they have set up.
There is no reason to add more color/detail to the chunk you are in, it's always the one directly in the center of the GUI.
